"""EmbeddingVector model for the RAG Pipeline."""
from dataclasses import dataclass, field
from datetime import datetime
from typing import List
from .base import BaseModel


@dataclass(kw_only=True)
class EmbeddingVector(BaseModel):
    """Represents the numerical vector representation of text chunks generated by Cohere models."""
    
    chunk_id: str
    vector: List[float]
    dimensions: int
    model_used: str
    
    def __post_init__(self):
        """Validate the EmbeddingVector after initialization."""
        if not self.chunk_id:
            raise ValueError("Chunk ID must not be empty")
        
        if not self.vector:
            raise ValueError("Vector must not be empty")
        
        if self.dimensions <= 0:
            raise ValueError("Dimensions must be positive")
        
        if len(self.vector) != self.dimensions:
            raise ValueError(f"Vector length ({len(self.vector)}) does not match dimensions ({self.dimensions})")
        
        if not self.model_used:
            raise ValueError("Model used must not be empty")